[features]
seeds = true
skip-lint = false
[programs.localnet]
pydraw = "Cncq6qR9Hd1xLveR6Z5vJWUkWYBPo75mqwHEfK2LRS17"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/callummcintyre/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
